config/routes.rb
Rails.application.routes.draw do
	root "bets#index"
	get "/up", to: "bets#arrow_up"
	get "/down", to: "bets#arrow_down"
	get "/status", to: "bets#status"
	get "/current_btc", to: "bets#current_btc"
	post "/send", to: "bets#sending"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
	has_many :gamblers, dependent: :destroy
end

app/models/gambler.rb
class Gambler < ApplicationRecord
	belongs_to :bet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

  def index
    @bets = Bet.all.order( 'id DESC' )
  	@bet_last = Bet.last
  end

  def arrow_up
  	@client_address = params["parameter"]
  	@client = Gambler.new
  	@client.client_address = @client_address
  	@client.bet_id = Bet.last.id
  	@client.up = true
  	@client.save
  	@bet_address = BlockIo.get_new_address(:label => "#{@client.id}")
  	@client.update(bet_address: @bet_address["data"]["address"])
  	
  	#When payment received update status to true
  	render json: @client
  end

  def arrow_down
  	@client_address = params["parameter"]
  	@client = Gambler.new
  	@client.client_address = @client_address
  	@client.bet_id = Bet.last.id
  	@client.down = true
  	@client.save
	  @bet_address = BlockIo.get_new_address(:label => "#{@client.id}")
  	@client.update(bet_address: @bet_address["data"]["address"])

  	#When payment received update status to true
  	render json: @client
  end

  def status
    @client_address_status = params["parameter"]
    @status = BlockIo.get_address_balance :addresses => @client_address_status
    @gambler_id = @status["data"]["balances"][0]["label"]
    @gambler = Gambler.find(@gambler_id)
    @gambler_bet = Bet.find(@gambler.bet_id)

    @json_hash = {}
    @json_hash["BlockIo"] = @status
    @json_hash["Gambler"] = @gambler
    @json_hash["Bet"] = @gambler_bet


    #when AJAX success render json hash of status
    render json: @json_hash
  end

  def current_btc
    @current_bet = Bet.last
    @up = []
    @down = []

    
    i = 0
    while i < @current_bet.gamblers.where.not(bet_address: nil).count do
      balance = BlockIo.get_address_balance :addresses => @current_bet.gamblers[i].bet_address
      if balance["data"]["available_balance"].to_f > 0 || balance["data"]["pending_received_balance"].to_f > 0
        if @current_bet.gamblers[i].up == true
            @up << balance["data"]["available_balance"].to_f
            @up << balance["data"]["pending_received_balance"].to_f
        else
            @down << balance["data"]["available_balance"].to_f
            @down << balance["data"]["pending_received_balance"].to_f
        end
      end
      i+=1
    end

    if @up.empty?
      @sum_up = 0
    else
      @sum_up = @up.inject(:+)
    end
    
    if @down.empty?
      @sum_down = 0
    else
      @sum_down = @down.inject(:+)
    end

    if @up.empty? && @down.empty?
      @sum = 0
    else
      @sum = @sum_up + @sum_down
    end

    @sums = {}  
    @sums["up"] = @sum_up
    @sums["down"] = @sum_down
    @sums["total"] = @sum

    render json: @sums
  end

  def sending
    @subject = params["subject"]
    @text = params["message"]
    ContactMailer.send_contact(@subject, @text).deliver_now
    flash[:notice] = "Mail sent"
    redirect_to root_path
  end
#private

	# def bet_params
	# 	params.require(:bet).permit(:base_price)	
	# end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/index.html.erb
<div class="container">
<!-- 	ROW 1: Title -->
	<div class="row center_title">
		<div class="row">
			<h1 class="text-success">BitBit, Bet on the hour <%= fa_icon "btc"%></h1>
			<p>
				1<i class="fa fa-btc" aria-hidden="true"></i> 
				= <span class="kraken_btc_eur">000.00</span> 
				<i class="fa fa-eur" aria-hidden="true"></i>
				(kraken.com: <a href="https://www.kraken.com/charts" target="_blank">Charts</a>)
			</p>
			<h4 class="click" data-toggle="modal" data-target=".bs-example-modal-lg"><mark>Betting with my bitcoins, how it works ?</mark></h4>
			<h4 class="bg-success"><%= flash[:notice]%></h4>		
		</div>
		<div class="row pad_1">
			<div class="col-xs-4">
				<%= fa_icon "user-secret 3x"%> 
				<p>Anonymous</p>	
			</div>
			<div class="col-xs-4">
				<%= fa_icon "user-times 3x"%>
				<p>No account</p>
			</div>
			<div class="col-xs-4">
				<%= fa_icon "arrows-v 3x"%>
				<p>Simple</p>
			</div>
		</div>
	</div>

<!-- 	ROW 2: current bet -->
	<div class="row pad">
		<div class="well center_arrows">
			<div class="row">
				<h4><p class="text-warning">Current bet</p></h4>
			</div>
			<div class="row">
				<div class="col-xs-3">
					<h3 id="current_bet_id"><%= @bet_last.id%></h3>
					<p>id</p>
				</div>
				<div class="col-xs-3">
					<h3 id="current_bet_base_price"><%= @bet_last.base_price%> <%= fa_icon "eur"%></h3>
					<p>base price</p>					
				</div>
				<div class="col-xs-3">
					<h3><span class="kraken_btc_eur">000.00</span> <%= fa_icon "eur"%></h3>
					<p>current price</p>					
				</div>
				<div class="col-xs-3">
					<h3 class="counter"></h3>
					<p>to end</p>					
				</div>
			</div>
		</div>
	</div>

<!-- 	ROW 3: Bet form -->
	<div class="row pad center_arrows">
		<div class="col-sm-6">
			<div class="row">
				<h4 class="text-primary">Bet on up or bet on down ?</h4>					
			</div>
			<div class="row">
				<div class="col-xs-4 text-success">
					<p class="click" data-toggle="modal" data-target=".bs-example-modal-sm3"><%= fa_icon "arrow-up 3x"%></p>
					<p id="current_up"> <%= fa_icon "btc"%></p>
				</div>
				<div class="col-xs-4">
					<p id="current_total"> <%= fa_icon "btc"%></p>
					<p class="counter"></p>
				</div>
				<div class="col-xs-4 text-danger">
					<p id="current_down"> <%= fa_icon "btc"%></p>
					<p class="click" data-toggle="modal" data-target=".bs-example-modal-sm4"><%= fa_icon "arrow-down 3x"%></p>
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<h4 class="text-primary">Check your bet status</h4>
			<div class="input-group">
				<input id="btc_address_status" type="text" class="form-control" aria-label="..." placeholder="BTC address you send the bet to">
				<div class="input-group-btn">
					<!-- Buttons -->
					<button id="bet_status" type="button" class="btn btn-default" aria-label="Status" data-toggle="modal" data-target=".bs-example-modal-sm5">Check status</button>
				</div>
			</div>
		</div>
	</div>

<!-- 	ROW 4: bet history -->
	<div class="row pad">
		<p>Prize fee: 5%</p>
		<table class="table table-striped">
			<thead> 
				<tr>
					<th>Id</th>
					<th>Period</th>
					<th>Base price</th>
					<th>Last price</th>
					<th>Status</th>
				</tr>
			</thead>
			<tbody id="bet_loop">
<!------------------------ LOOP ---------------------------->
				<% @bets.each do |bet|%>
 				<tr>
					<th scope="row"><%= bet.id%></th>
					<td><%= bet.created_at%></td>
					<td><%= bet.base_price%> <%= fa_icon "eur"%></td>

					<% if bet.last_price.nil?%>
						<td><span class="kraken_btc_eur"></span> <%= fa_icon "eur"%></td>
					<%else%>
						<%if bet.result == "up"%>
							<td><%= bet.last_price%> <%= fa_icon "eur"%> <%= fa_icon "arrow-up", class: "Active"%></td>
						<%else%>
							<td><%= bet.last_price%> <%= fa_icon "eur"%> <%= fa_icon "arrow-down", class: "Closed"%></td>
						<%end%>
					<%end%>
					
					<td class="<%=bet.status%>"><%= bet.status%></td>
				</tr>
<!------------------------ END LOOP ------------------------>
				<%end%>
			</tbody>
		</table>		
	</div>

<!-- Footer -->
    <footer>
        <div class="row inline">
         	<p>Copyright &copy; BitBit <%= Time.now.year%></p>
         	<p class="click" data-toggle="modal" data-target=".bs-example-modal-sm1">Contact</p>
        </div>
    </footer>
</div>

<!-- Small modal How it works ? -->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
		<dl class="center_arrows">
	  		<dt>
				<p class="text-primary">What is BitBit, bet on the hour (Bitcoin Betting)?</p>		  	
	  		</dt>
	  		<dd>
	  			It’s a website where Bitcoin exchange rate against EUR is used so that you to bet on its value going up or down by the end of the current hour. The exchange rate is retrieved from <a href="https://www.kraken.com/charts" target="_blank">Kraken.com</a>.
	  		</dd>
	  		<dt>
				<p class="text-primary">Brief description</p>		  	
	  		</dt>
	  		<dd>
				Every hour, the BTC/EUR exchange rate is fixed at the last price (base price), and you can bet on the rise or fall of the exchange rate in relation to the base price. After the hour interval, the bet is closed, and a new hour bet acceptance period with a new base price begins.
				After the betting period is over, the BTC/EUR exchange rate is fixed at the last price, and the drawing is made. If you placed an up bet and the price went up, you will receive a prize as a percentage of your bet to the total amount of up bets. In this case, the prize pool is the sum of all down bets. The same algorithm is applied to down bets, but vice versa. After the Bet is closed, it takes 2 hours to receive your winning funds.

	  		</dd>
	  		<dt>
				<p class="text-primary">Some rules to have in mind:</p>		  	
	  		</dt>
	  		<dd>
	  			<ul>
	  			 	<li>Minimum bet is 0.01 BTC</li>
	  			 	<li>BitBit take 5% service commision on your winning funds</li>
	  			 	<li>Do not bet after the bet is closed</li>
	  			 	<li>Take into account bitcoin network fees</li>
	  			 	<li>If no winners; all loosers are refunded and vice versa</li>
	  			 	<li>If the BTC/EUR value remained the same after the bet close, everyone get refunded</li>
	  			 </ul> 
	  		</dd>
	  		<dt>
				<p class="text-primary">Checking your bet status</p>		  	
	  		</dt>
	  		<dd>
				The Bitcoin address address generated to fund your bet can be used to check your bet status and to track your payout.

	  		</dd>	  		
	  		<dt>
				<p class="text-primary">Example in action for better understanding:</p>		  	
	  		</dt>
	  		<dd>
	  			Let's say you bet 0.04 btc on up. The base price of the bet is 1000€ and at closing it went up to 1020€, thus you win. The total of bitcoins that were bet on up was 0.20 and those bet on down was 0.80. Therefore, your bet was accounting for 20% of the bitcoins bet on up: (0.04/0.20)*100 (the percentage of your bet to the total sum of the same bet outcome).
	  			The total of bitcoins bet on down was 0.80, hence you win 20% of the 0.8 which is 0.16.
	  			From the 0.16 you will be discounted 5% of service commission which will take your net winning fund to 0.152.
	  		</dd>	  			  		
		</dl>
    </div>
  </div>
</div>

<!-- Small modal contact form-->
<div class="modal fade bs-example-modal-sm1" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Send a message to BitBit team</h4>
      </div>
      <%= form_tag(send_path, method: "POST", class: "form-horizontal") do%>
	      <div class="modal-body">
	        <div class="form-group">
	        	<%= label_tag(:subject, "Subject", class: "col-sm-2") %>
	            <div class="col-sm-10">
	          		<%= text_field_tag(:subject, content = nil, class: "form-control") %>
	            </div>
	        </div>
	        <div class="form-group">
	        	<%= label_tag(:message, "Message", class: "col-sm-12") %>
	          	<div class="col-sm-12">
	          		<%= text_area_tag(:message, content = nil, class: "form-control") %>
	          	</div>
	        </div>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button> 
	        <%= submit_tag 'Send', class: "btn btn-primary" %>        
	      </div>
      <%end%>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal compose message -->

<!-- Arrow up -->
<div class="modal fade bs-example-modal-sm3" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div id="arrow_up_btc" class="modal-content pad">
    	<p class="bg-warning">Bitcoin sent will be bet on UP</p>

		<h6 class="text-primary center_arrows">Enter the Bitcoin address where you would like to receive your winnings</h6>
		<div class="input-group">
			<input id="client_btc_address_up" type="text" class="form-control" aria-label="..." placeholder="Bitcoin address">
			<div class="input-group-btn">
				<!-- Buttons -->
				<button id="bet_up" type="button" class="btn btn-default" aria-label="Help">Bet Up</button>
			</div>
		</div>				
    </div>
  </div>
</div>

<!-- Arrow down -->
<div class="modal fade bs-example-modal-sm4" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div id="arrow_down_btc" class="modal-content pad">
    	<p class="bg-warning">Bitcoin sent will be bet on DOWN</p>

		<h6 class="text-primary center_arrows">Enter the Bitcoin address where you would like to receive your winnings</h6>
		<div class="input-group">
			<input id="client_btc_address_down" type="text" class="form-control" aria-label="..." placeholder="Bitcoin address">
			<div class="input-group-btn">
				<!-- Buttons -->
				<button id="bet_down" type="button" class="btn btn-default" aria-label="Help">Bet Down</button>
			</div>
		</div>				
    </div>
  </div>
</div>

<!-- Status-->
<div class="modal fade bs-example-modal-sm5" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div id="modal_status" class="modal-content">
     
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetBit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>